version: '3.9'
services:
  web:
    image: futscraper
    privileged: true
    build: .
    env_file:
      - .env-staging
    command: gunicorn futscraper.wsgi:application --bind 0.0.0.0:8000 --limit-request-line 0 --access-logfile gunicorn.log --workers=4
    volumes:
      - static:/application/staticfiles
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/application/static/:ro
      - ./nginx/staging-conf/:/etc/nginx/conf.d/:ro
    restart: "unless-stopped"
    depends_on:
      web:
        condition: service_started

volumes:
  static:
    driver: local
