# Generated by Django 4.0.6 on 2022-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('ea_email', models.EmailField(max_length=240)),
                ('ea_password', models.CharField(max_length=100)),
                ('chrome_profile', models.CharField(max_length=200)),
            ],
        ),
    ]
